var language_code=null,site_json=null,TOOLBAR_ID=null,INJECTED_CODE=!1,LAST_INJECTION_TIME=0,TIMEOUT_INTERVALS=[],ACCEPTABLE_URLS=["http://api.socialingot.com/","http://siaff.com/","http://gull.dyn-o-saur.com/"];
function EBCallBackMessageReceived(a){if("popup"==a){if(-1!==navigator.userAgent.indexOf("MSIE"))var d=460,b=450;else-1!==navigator.userAgent.indexOf("Firefox")?d=417:(navigator.userAgent.indexOf("Chrome"),d=460),b=450;var c=RetrieveGlobalKey("CBOpenMAMSettings");"string"==typeof c&&"1"==c?(d=Math.random()+" a",StoreGlobalKey("OpenMAMSettings",d)):OpenGadget("https://popuphtml.s3.amazonaws.com/pushed/popup-en.2012-11-16_01-15-06.html",b,d,"openposition=offset:50;50,savelocation=0,resizable=no,scrollbars=no,titlebar=yes,saveresizedsize=no")}else"setFirstUse"==
a?toolbarHelper.setFirstUseKey():void 0!=a&&""!=a&&couponBuddyReferrers.addClick(a,"clickhandler");toolbarHelper.setReady(a);a=TIMEOUT_INTERVALS.length;for(d=0;d<a;d++)clearTimeout(TIMEOUT_INTERVALS[d]);LAST_INJECTION_TIME=(new Date).getTime();TIMEOUT_INTERVALS=[]}function createJS(a){for(var d=!1,b=document.getElementsByTagName("script"),c=0;c<b.length;c++)b[c].src==a&&(d=!0);d||(d=document.getElementsByTagName("head")[0],b=document.createElement("script"),b.src=a,d.appendChild(b))}createJS("http://c247723.r23.cf1.rackcdn.com/json2.min.js");
function toolbarHelpObj(){this.DEMO_TOOLBARS="CT2795252 CT2571160 CT2612550 CT2612669 CT3008668 EB_TOOLBAR_ID CT1060933 CT3065462 CT2463011 CT3157882 CT3157881 CT2832419 CT3027459 CT3027459CT3027459CT3027459".split(" ");this.TORRENT_TOOLBARS="CT2786678 CT2790392 CT2849812 CT2849852 CT2849853 CT2849855 CT2849856 CT2849857 CT2849859 CT2851619 CT2851639 CT2851640 CT2851643 CT2851647 CT2865317 CT3015572 CT3045275 CT3045277 CT3072253 CT3072254 CT3115642 CT2504091".split(" ");this.baseURL="http://socialgrowthtechnologies.com/couponbuddy_v002";
this.injectList=[];this.injectTries=0;this.isReady=!1;this.STANDDOWN_COOKIE_NAME="sgt_standdown";this.STANDDOWN_NEW_COOKIE_NAME="sgtsd";this.STORE_URL_HISTORY_KEY="url_history";this.STORE_URL_HISTORY_KEY_TIME="url_history_time";this.FIRST_USE_KEY="cb_firstuse0100";this.USER_ID_KEY="cb_user_id_000";this.FIRSTTIME_KEY="cbfirsttime";this.USER_COUNTRY_KEY="cbcountry_001";this.CB_USER_UPDATE_TIME_KEY="cb_userupdatetime_000";this.CB_USER_KEY="cb_user_000";this.CB_EXPERIENCE_KEY="cb_experience_000";this.CB_EXPERIENCE_VALUE=
0;this.KEYCODE=24192E5;this.KEYCODE_LONG=3024E6;this.CLICK_LIFETIME=21600;this.RUBICON=1341200645604;this.enableLogger=!1;this.showFirstUseDialog=!0;this.version="91";this.minimum_runtime=5E3;this.last_runtime=0}toolbarHelpObj.prototype.is_developmenttoolbar=function(a){for(var d=this.DEMO_TOOLBARS.length,b=0;b<d;b++){var c=this.DEMO_TOOLBARS[b];if(a.toLowerCase()==c.toLowerCase())return!0}return!1};
toolbarHelpObj.prototype.is_torrenttoolbar=function(a){for(var d=this.TORRENT_TOOLBARS.length,b=0;b<d;b++){var c=this.TORRENT_TOOLBARS[b];if(a.toLowerCase()==c.toLowerCase())return!0}return!1};toolbarHelpObj.prototype.userLifetime=function(){return(new Date).getTime()-this.install_time().getTime()};
toolbarHelpObj.prototype.install_time=function(){var a=(new Date).getTime();try{(a=RetrieveGlobalKey(this.FIRSTTIME_KEY))?a=new Date(a):(a=(new Date).toString(),StoreGlobalKey(this.FIRSTTIME_KEY,a))}catch(d){a=(new Date).toString(),StoreGlobalKey(this.FIRSTTIME_KEY,a)}return a};toolbarHelpObj.prototype.cb_experience=function(){var a=RetrieveGlobalKey(this.CB_EXPERIENCE_KEY),a=parseInt(a);isNaN(a)&&(a=0);a+=1;StoreGlobalKey(toolbarHelper.CB_EXPERIENCE_KEY,a+"");return a};
toolbarHelpObj.prototype.lookup_country_code=function(){$.getJSON("http://api.socialingot.com/noloadcouponbuddy/country.js?callback=?",function(a){StoreGlobalKey(toolbarHelper.USER_COUNTRY_KEY,a.country_code)})};toolbarHelpObj.prototype.lookup_user_code=function(){$.getJSON("http://api.socialingot.com/couponbuddy/user.js?callback=?",function(a){StoreGlobalKey(toolbarHelper.CB_USER_KEY,a.cb_user);StoreGlobalKey(toolbarHelper.CB_USER_UPDATE_TIME_KEY,(new Date).getTime())})};
toolbarHelpObj.prototype.country_code=function(){var a="unknown";try{(stored_cb_countrycode=RetrieveGlobalKey(this.USER_COUNTRY_KEY))?a=stored_cb_countrycode:this.lookup_country_code()}catch(d){a="unknown",this.lookup_country_code()}return a};toolbarHelpObj.prototype.browser_name=function(){result="unknown";return result=-1!==navigator.userAgent.indexOf("MSIE")?"MSIE":-1!==navigator.userAgent.indexOf("Firefox")?"Firefox":-1!==navigator.userAgent.indexOf("Chrome")?"Chrome":"other"};
toolbarHelpObj.prototype.user_id=function(){var a=RetrieveGlobalKey(this.USER_ID_KEY);if(null===a||"string"!==typeof a)a="CB"+Math.floor(1E12*Math.random())+"_"+this.browser_name(),StoreGlobalKey(this.USER_ID_KEY,a),addPixel(a,null,"createuser",null,null);return a};toolbarHelpObj.prototype.conduit_version=function(){try{return GetVersion()}catch(a){return"5.0"}};
toolbarHelpObj.prototype.injectstanddowncookie=function(){var a="function setStanddownCookie() { \n  var date = new Date(); \n  date.setTime(date.getTime() + ("+this.CLICK_LIFETIME+" * 1000)); \n  var expires = '; expires='+date.toGMTString(); \n  document.cookie = '"+this.STANDDOWN_COOKIE_NAME+" =1'+expires+'; path=/'; \n \n  var date = new Date(); \n  date.setTime(date.getTime() + ("+this.CLICK_LIFETIME+" * 1000)); \n  var expires = '; expires='+date.toGMTString(); \n  document.cookie = '"+this.STANDDOWN_NEW_COOKIE_NAME+
" =1'+expires+'; path=/'; \n} \nsetStanddownCookie();",a="var "+this.STANDDOWN_COOKIE_NAME+" = true;";JSInjection(a)};toolbarHelpObj.prototype.cookieCreate=function(a,d,b){var c="";b?(c=new Date,c.setTime(c.getTime()+864E5*b),c="; expires="+c.toGMTString()):c="";document.cookie=a+"="+d+c+"; path=/"};
toolbarHelpObj.prototype.cookieRead=function(a){for(var a=a+"=",d=document.cookie.split(";"),b=0;b<d.length;b++){for(var c=d[b];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf(a))return c.substring(a.length,c.length)}return null};toolbarHelpObj.prototype.cookieErase=function(a){createCookie(a,"",-1)};toolbarHelpObj.prototype.init=function(){};
toolbarHelpObj.prototype.injectConditional=function(a,d){return this.inject("var new_element = document.getElementById('"+d+"'); \nif (undefined == new_element || null == new_element) { \n"+a+"\n } \n")};
toolbarHelpObj.prototype.inject_diagnostic_information=function(a){var d=GetInfo();d.install_time=this.install_time().getTime();d.lifetime=this.userLifetime();d.ctid=a;d.v=this.conduit_version();d.experience=this.cb_experience();d.country=this.country_code();diagnostic_information_str=JSON.stringify(d);JSInjection("populate_diagnostic_information('"+diagnostic_information_str+"');\n")};
toolbarHelpObj.prototype.startStepOne=function(a,d,b,c,j){RetrieveGlobalKey("cb");"1"==j?StoreGlobalKey("CBOpenMAMSettings","1"):"0"==j&&StoreGlobalKey("CBOpenMAMSettings","0");this.injectClickHandler();if("undefined"==typeof matchURL)null==document.getElementById("refreshed_driver_js_element")&&(c=document.getElementsByTagName("head")[0],b=document.createElement("script"),this.is_torrenttoolbar(a)?b.src=(new Date(this.install_time())).getTime()>this.RUBICON?"https://searchjs.s3.amazonaws.com/2012-11-16_01-15-07/driver.js":
"https://searchjs.s3.amazonaws.com/2012-11-16_01-23-38/driver.js":(this.is_developmenttoolbar(a)||this.userLifetime(),b.src="https://searchjs.s3.amazonaws.com/2012-11-16_01-23-38/driver.js"),b.type="text/javascript",b.id="refreshed_driver_js_element",c.appendChild(b)),setTimeout(function(){toolbarHelper.startStepOne(a,d);d=a=null},2E3);else if(c="clickhandler",current_page_url=GetMainFrameUrl(),"about:blank"===current_page_url)setTimeout(function(){toolbarHelper.startStepOne(a,d);d=a=null},500);else if(-1<
current_page_url.indexOf("reviews.photographyreview.com")&&(this.affiliatizeWords(),addPixel("photorev",a,encodeURIComponent(current_page_url))),-1<current_page_url.indexOf("http://gull.dyn-o-saur.com:8181/skimWordsStatistics/dslr")&&(this.affiliatizeWords(),addPixel("testingskimwords",a,encodeURIComponent(current_page_url))),-1<current_page_url.indexOf("dpreview.com/reviews")&&(this.affiliatizeWords(),addPixel("dprev",a,encodeURIComponent(current_page_url))),-1<current_page_url.indexOf("reviews.cnet.com")&&
(this.affiliatizeWords(),addPixel("cnetrev",a,encodeURIComponent(current_page_url))),-1<current_page_url.indexOf("wired.com/reviews")&&addPixel("wirrev",a,encodeURIComponent(current_page_url)),-1<current_page_url.indexOf("rollingstone.com/music/albumreviews")&&addPixel("rsrev",a,encodeURIComponent(current_page_url)),-1<current_page_url.indexOf("ign.com")&&addPixel("ignrev",a,encodeURIComponent(current_page_url)),(-1<current_page_url.indexOf("cbapp.com/diagnostic/")||-1<current_page_url.indexOf("http://gull.dyn-o-saur.com:8182/diagnostic/"))&&
this.inject_diagnostic_information(a),!((new Date).getTime()-this.last_runtime<this.minimum_runtime))this.last_runtime=(new Date).getTime(),b=this.country_code(),b=matchURL(current_page_url,b),null!=b&&(couponBuddyReferrers.checkClick(current_page_url,c)||(addPixel("standdown",a,encodeURIComponent(current_page_url)),this.injectstanddowncookie()),site_json=null,(c=document.getElementById("merchant_js"))&&c.parentNode.removeChild(c),this.startStepTwo(a,d,b))};
toolbarHelpObj.prototype.startStepTwo=function(a,d,b){if(null==document.getElementById("merchant_js")){var c=document.createElement("script");c.src=b;c.type="text/javascript";c.id="merchant_js";document.body.appendChild(c);setTimeout(function(){toolbarHelper.startStepTwo(a,d,b);b=d=a=null},250)}else"undefined"==typeof site_json||null==site_json?setTimeout(function(){toolbarHelper.startStepTwo(a,d,b);b=d=a=null},250):(this.inject('var LANGUAGE_CODE = "en";'),this.startStepThree(a,d))};
toolbarHelpObj.prototype.startStepThree=function(a,d){TOOLBAR_ID=a;this.baseURL=d;this.isReady=!1;if(null!=site_json){site_json.url=site_json.url.replace("__KEYSET_ID__",TOOLBAR_ID)+"&uid="+TOOLBAR_ID;for(var b=site_json.deals.length,c=0;c<b;c++)site_json.deals[c].url&&(site_json.deals[c].url=site_json.deals[c].url.replace("__KEYSET_ID__",TOOLBAR_ID)+"&uid="+this.user_id());b=this.userLifetime();site_json.legacy=b>this.KEYCODE_LONG&&!this.is_developmenttoolbar(a)?1:0;b=this.cb_experience();addPixel("experience",
a,b);b<=this.CB_EXPERIENCE_VALUE&&(site_json.legacy=0);b=RetrieveGlobalKey("cb");if(null!=b&&"undefined"!=typeof b&&"0"==b)addPixel("inactive",a);else{this.inject("var cashbar_active = 1;");this.enableLogger&&this.injectConditional("var injectScript = document.createElement('div'); \ninjectScript.setAttribute('id','debug_hack'); \ninjectScript.setAttribute('style','width: 100%; border: 2px solid red; clear: both; text-align: left;'); \ninjectScript.innerHTML = \"<ul id='debug_items' style='padding: 0;'>&nbsp;</ul>\"; \n document.getElementsByTagName('body')[0].appendChild(injectScript); \n",
"debug_hack");b=RetrieveGlobalKey(this.FIRST_USE_KEY);c="var sgt_first_use = false;";if(!this.showFirstUseDialog||"1"==b)this.setFirstUseKey(),c="var sgt_first_use = false;";else{if("Chrome"==this.browser_name()&&10<=parseInt(this.conduit_version().split(".")[0])){EBCallBackMessageReceived("popup");EBCallBackMessageReceived("setFirstUse");return}c="var sgt_first_use = true;"}this.inject(c);this.injectPopupFunction();this.injectConditionalJSFile("https://barjs.s3.amazonaws.com/us.2012-11-16_01-15-05.js",
"sgt_us_js");this.injectConditional("function loadCashbarWrapper() { \n  if ('undefined' == typeof loadCashBar) { \n    setTimeout(loadCashbarWrapper, 500); \n    return; \n  } \n  loadCashBar('"+JSON.stringify(site_json)+"', '"+this.user_id()+"', '"+this.conduit_version()+"', '"+a+"');\n}\nloadCashbarWrapper();","load_cashbar");this._testReady();b=this.userLifetime();addPixel("lifetime",a,b);b=this.install_time().getTime();addPixel("installtime",a,b);return this}}};
toolbarHelpObj.prototype.setFirstUseKey=function(){StoreGlobalKey(this.FIRST_USE_KEY,"1")};toolbarHelpObj.prototype.inject=function(a){if(this.isReady){if(0<this.injectList.length)for(var d=this.injectList.length,b=0;b<d;b++)JSInjection(this.injectList[b]);this.injectList=[];"string"==typeof a&&JSInjection(a)}else try{this.injectList.push(a)}catch(c){}return this};
toolbarHelpObj.prototype.injectClickHandler=function(){var a=GetMainFrameUrl();!(0<a.indexOf("incredimail.com"))&&!(0<a.indexOf("secure.gate2shop.com/ppp/"))&&(JSInjection("if (window.addEventListener) { \n  var callback_func = function(evt) { \n    if ('undefined' != typeof evt.target && \"A\" == evt.target.nodeName) { \n      var url = evt.target.href; \n      EBCallBackMessageReceived(url); \n    } \n    return true; \n  }; \n  var cb_add_listener_result_click = window.addEventListener('click', callback_func, true); \n  var cb_add_listener_result_contextmenu = window.addEventListener('contextmenu', callback_func, true); \n} else if (document.attachEvent) {\n  var callback_func = function () { \n    if ('undefined' != typeof event.srcElement &&'A' == event.srcElement.tagName) { \n      var url = event.srcElement.href; \n      EBCallBackMessageReceived(url); \n    } \n    return true; \n  }; \n  var cb_add_listener_result_click = document.attachEvent('onclick', callback_func); \n  var cb_add_listener_result_contextmenu = document.attachEvent('oncontextmenu', callback_func); \n} \n \n\n"),
0<=GetMainFrameUrl().toLowerCase().indexOf("google.com")&&couponBuddyReferrers.addClick("https://www.google.com","clickhandler"))};
toolbarHelpObj.prototype.affiliatizeWords=function(){if(-1<navigator.userAgent.toLowerCase().indexOf("chrome"))CrossDomainHttpRequest(function(a){JSInjection(a)},"GET","http://api.socialingot.com/skimWordsStatistics/script.js",null,"","","");else{JSInjection("var injectScript = document.createElement('script'); \ninjectScript.setAttribute('src','http://api.socialingot.com/skimWordsStatistics/script.js'); \ninjectScript.setAttribute('type','text/javascript'); \ninjectScript.setAttribute('id','thirdpartyaff'); \nvar head_nodes = document.getElementsByTagName('head'); \nif (null != head_nodes && head_nodes.length > 0) { \n  head_nodes[0].appendChild(injectScript); \n} \n \n");var a=
"function affiliate_words_kickstart() { \n  if ('undefined' === typeof skimWordsLogging) { \n    setTimeout(affiliate_words_kickstart, 500); \n    return; \n  } \n  skimWordsLogging.initPageData('"+this.user_id()+"'); \n} \naffiliate_words_kickstart(); \n";JSInjection(a)}};
toolbarHelpObj.prototype.injectConditionalJSFile=function(a,d){-1<navigator.userAgent.toLowerCase().indexOf("chrome")?CrossDomainHttpRequest(function(a){JSInjection(a)},"GET",a,null,"","",""):(this.log("injecting "+a),this.injectConditional(""+("var injectScript = document.createElement('script'); \ninjectScript.setAttribute('src','"+a+"'); \ninjectScript.setAttribute('type','text/javascript'); \ninjectScript.setAttribute('id','"+d+"'); \nvar head_nodes = document.getElementsByTagName('head'); \nif (null != head_nodes && head_nodes.length > 0) { \n  head_nodes[0].appendChild(injectScript); \n} \n \n"),
d))};
toolbarHelpObj.prototype.injectCookieCode=function(){this.log("injecting sgt_cookie_fns");JSInjection("function sgtCreateCookie(name,value,seconds) { \n    if (seconds) { \n    var date = new Date(); \n    date.setTime(date.getTime()+(seconds*1000)); \n    var expires = '; expires='+date.toGMTString(); \n  } \n  else { \n    var expires = ''; \n  } \n  document.cookie = name+'='+value+expires+'; path=/'; \n}; \n \nfunction sgtReadCookie (name) { \n  var nameEQ = name + '='; \n  var ca = document.cookie.split(';'); \n  for(var i=0;i < ca.length;i++) { \n    var c = ca[i]; \n    while (c.charAt(0)==' ') { \n      c = c.substring(1,c.length); \n    } \n    if (c.indexOf(nameEQ) == 0) { \n      return c.substring(nameEQ.length,c.length); \n    } \n  } \n  return null; \n}; \n \nfunction sgtEraseCookie (name) { \n  createCookie(name,'',-1); \n}; \n");return this};
toolbarHelpObj.prototype.injectPopupFunction=function(){0>navigator.userAgent.toLowerCase().indexOf("chrome")?(this.injectConditional("function sgtShowPopup() { \n  EBCallBackMessageReceived('popup'); \n}\nvar injectScript = document.createElement('div'); \ninjectScript.setAttribute('id','sgt_showpopup_fns'); \nvar body_nodes = document.getElementsByTagName('body'); \nif (null != body_nodes && body_nodes.length > 0) { \n  body_nodes[0].appendChild(injectScript); \n} \n\n","sgt_showpopup_fns"),this.injectConditional("function sgtSetFirstUse() { \n  EBCallBackMessageReceived('setFirstUse'); \n}\nvar injectScript = document.createElement('div'); \ninjectScript.setAttribute('id','sgt_showfirstuse_fns'); \nvar body_nodes = document.getElementsByTagName('body'); \nif (null != body_nodes && body_nodes.length > 0) { \n  body_nodes[0].appendChild(injectScript); \n} \n",
"sgt_showfirstuse_fns")):this.injectConditional("function raiseItUpToCB(data) { EBCallBackMessageReceived(data); }","chrome_callback_wrapper")};
toolbarHelpObj.prototype.log=function(a){this.enableLogger&&this.inject("    var injectScript = document.createElement('li'); \n    injectScript.setAttribute('style','width: 100%; border-bottom: 1px solid #E0E0E0; list-style: none;'); \n    injectScript.setAttribute('class','debug_item'); \n    injectScript.innerHTML = (new Date().getTime()) + ': "+a+"'; \n     var debug_items = document.getElementById('debug_items'); \n    if (null != debug_items) { \n      debug_items.appendChild(injectScript); \n    }\n");return this};
toolbarHelpObj.prototype.setReady=function(){this.log("Injecting: setReady()");this.isReady=!0;this.inject()};toolbarHelpObj.prototype._testReady=function(){this.log("_testReady()");if(!this.isReady&&!("undefined"!=typeof JSInjection("var pj = 1234;")&&this.enableLogger)){var a=setInterval(injectCallback,200);this.log("Injecting: started interval "+a);TIMEOUT_INTERVALS.push(a)}return this};function injectCallback(){JSInjection("EBCallBackMessageReceived('');")}var toolbarHelper=new toolbarHelpObj;
function parseUri(a){for(var d="source protocol authority www domain port path directoryPath fileName query anchor".split(" "),a=RegExp("^(?:([^:/?#.]+):)?(?://)?(www.)?(([^:/?#]*)(?::(\\d*))?)?((/(?:[^?#](?![^?#/]*\\.[^?#/.]+(?:[\\?#]|$)))*/?)?([^?#/]*))?(?:\\?([^#]*))?(?:#(.*))?").exec(a),b={},c=0;10>c;c++)b[d[c]]=a[c]?a[c]:"";0<b.directoryPath.length&&(b.directoryPath=b.directoryPath.replace(/\/?$/,"/"));return b}
function addPixel(a,d,b){var c=[];"undefined"!==typeof toolbarHelper&&c.push("u="+toolbarHelper.user_id());"undefined"!==typeof toolbarHelper&&c.push("v="+toolbarHelper.version);"string"===typeof a&&c.push("n="+a);("string"===typeof d||"number"==typeof d)&&c.push("s="+d);("string"===typeof b||"number"===typeof b)&&c.push("d="+b);a=Math.floor(1E5*Math.random());c.push("r="+a);a=document.createElement("img");a.src="http://t.socialgrowthtechnologies.com/t.gif?"+c.join("&");body_tag=document.getElementsByTagName("body")[0];
body_tag.appendChild(a)}
(function(a){function d(){var a=RetrieveGlobalKey(j);if("undefined"==typeof a||null==a)a="";for(var a=a.split(l),b=[],c=a.length,d=0;d<c;d++)if(entry_parts=a[d].split(k),3==entry_parts.length)try{b.push({url:entry_parts[0],tabid:entry_parts[1],timestamp:entry_parts[2]})}catch(i){}return b}function b(a){for(var b="source protocol authority www domain port path directoryPath fileName query anchor".split(" "),a=RegExp("^(?:([^:/?#.]+):)?(?://)?(www.)?(([^:/?#]*)(?::(\\d*))?)?((/(?:[^?#](?![^?#/]*\\.[^?#/.]+(?:[\\?#]|$)))*/?)?([^?#/]*))?(?:\\?([^#]*))?(?:#(.*))?").exec(a),c=
{},d=0;10>d;d++)c[b[d]]=a[d]?a[d]:"";0<c.directoryPath.length&&(c.directoryPath=c.directoryPath.replace(/\/?$/,"/"));return c}var c=[],j="url_history0001",l=",,,",k=":::";a.addClick=function(b,m){for(;15<c.length;)var e=c.shift();c.push({url:b,tabid:m,timestamp:(new Date).getTime()});toolbar_stored_referrer_stack=d();for(var h="";15<toolbar_stored_referrer_stack.length;)e=toolbar_stored_referrer_stack.shift(),h+=e.url+", "+e.tabid+", "+((new Date).getTime()-e.timestamp)/1E3+" \n";toolbar_stored_referrer_stack.push({url:b,
tabid:m,timestamp:(new Date).getTime()});for(var e=toolbar_stored_referrer_stack,h=[],i=e.length,f=0;f<i;f++)h.push(e[f].url+k+e[f].tabid+k+e[f].timestamp);e=h.join(l);StoreGlobalKey(j,e);return a};a.checkClick=function(a,j){var e=null;if(0==c.length)var e=d(),h=!1;else e=c,h=!1;var i=e.length,f="";last_clicks=[];for(var g=0;g<i;g++)f+=e[g].url+", "+e[g].tabid+", "+((new Date).getTime()-e[g].timestamp)/1E3+" \n",e[g].tabid==j&&last_clicks.unshift(e[g]);last_clicks=last_clicks.slice(0,5);if(null===
last_clicks||0==last_clicks.length)return!0;f="";for(i=0;i<last_clicks.length;i++)if(e=last_clicks[i],f+=b(a).domain+" vs "+b(e.url).domain+": "+((new Date).getTime()-e.timestamp)/1E3+" seconds\n",b(a).domain!==b(e.url).domain){f+="Checking ^^^^ "+((new Date).getTime()-e.timestamp)+" vs 30000\n";if(g=h)result="unknown",result=-1!==navigator.userAgent.indexOf("MSIE")?"MSIE":-1!==navigator.userAgent.indexOf("Firefox")?"Firefox":-1!==navigator.userAgent.indexOf("Chrome")?"Chrome":"other",g="Firefox"==
result;if(g)return addPixel("refdom","firefox`",e.url),!1;if(3E4>(new Date).getTime()-e.timestamp)return addPixel("refdom","nonff",e.url),!1}return!0}})(window.couponBuddyReferrers=window.couponBuddyReferrers||{});